name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Clang
      # You may pin to the exact commit or the version.
      # uses: egor-tensin/setup-clang@ef434b41eb33a70396fb336b1bae39c76d740c3d
      uses: egor-tensin/setup-clang@v1
    - name: Install GCC
      # You may pin to the exact commit or the version.
      # uses: egor-tensin/setup-gcc@eaa888eb19115a521fa72b65cd94fe1f25bbcaac
      uses: egor-tensin/setup-gcc@v1
    - name: Configure project
      run: |
        ./configure
    - name: Install code checker
      run: |
        pip3 install codechecker
    - name: Run CodeChecker
      run: |
        CodeChecker log --build "make clean; make" --output ./compile_commands.json
    - name: Analyze Build Reports
      run: |
        CodeChecker analyze ./compile_commands.json --enable sensitive --output ./reports
    - name: Produce CodeChecker Reports
      run: |
        CodeChecker parse --export html --output ./reports_html ./reports
    - name: Commit Reports Back to Repo
      run: |
        git add reports_html
        git commit -m "Add CodeChecker Reports"
        git push origin master
    
    
